### ISSUE TITLE
this.reserved is not a function

### ISSUE THREAD

**Issue by siddo420** [primus/primus-emit#4] opened 2015-12-15 23:42 UTC
Node.js crashes if I simply emit an event from client on a substream.
```js
primus.on('open', function open() {			
  substr.write({ emit: [ 'source', { name: 'this source' } ] });
});
```
on server, I am listening to it on spark.
```js
spark.on('source', function (data) {
  Logger.errorc('Source is : ' + JSON.stringify(data));
});
```

I understand this is not correct way of handling events (because substreams do not emit events) but it should at least not crash the node.js process.

```
error: uncaughtException: this.reserved is not a function date=Tue Dec 15 2015 18:35:18 GMT-0500 (EST),
pid=16890,
uid=501,
gid=20,
cwd=/node-web-projects/test3,
execPath=/usr/local/bin/iojs,
version=v5.0.0,
argv=[/usr/local/bin/iojs,
/node-web-projects/test3/app.js],
rss=95498240,
heapTotal=72151296,
heapUsed=53185288,
loadavg=[2.02734375,
1.9970703125,
1.85595703125],
uptime=127174,
trace=[column=15,
file=/node-web-projects/test3/node_modules/primus-emit/index.js,
function=SubStream.incoming,
line=70,
method=incoming,
native=false,
column=33,
file=/node-web-projects/test3/node_modules/primus/spark.js,
function=transform,
line=331,
method=null,
native=false,
column=4,
file=/node-web-projects/test3/node_modules/primus/spark.js,
function=Sparky.transforms,
line=349,
method=transforms,
native=false,
column=17,
file=/node-web-projects/test3/node_modules/substream/substream.js,
function=SubStream.mine,
line=166,
method=mine,
native=false,
column=33,
file=/node-web-projects/test3/node_modules/substream/index.js,
function=Sparky.incoming,
line=102,
method=incoming,
native=false,
column=33,
file=/node-web-projects/test3/node_modules/primus/spark.js,
function=transform,
line=331,
method=null,
native=false,
column=14,
file=/node-web-projects/test3/node_modules/primus/spark.js,
function=transform,
line=340,
method=null,
native=false,
column=14,
file=/node-web-projects/test3/node_modules/primus/spark.js,
function=transform,
line=340,
method=null,
native=false,
column=4,
file=/node-web-projects/test3/node_modules/primus/spark.js,
function=Sparky.transforms,
line=349,
method=transforms,
native=false,
column=13,
file=/node-web-projects/test3/node_modules/primus/spark.js,
function=decoding,
line=214,......
```

**Comment by lpinca** [comment] 2015-12-16 17:27
This will hopefully be fixed by #6.

**Comment by siddo420** [comment] 2015-12-16 17:54
when will it be available in the main branch ie. by updating the repository thru npm?

**Comment by lpinca** [comment] 2015-12-16 18:33
After @3rd-Eden review.

**Comment by lpinca** [comment] 2015-12-16 20:24
I flagged this as bug because it crashes the process, but it's caused by an ad hoc packet which isn't/shouldn't be used in practice. Incoming data should be validated to prevent this kind of problems/attack vectors.
In short, its not really a bug.

**Closed** 2015-12-17 14:54 UTC
Labels: bug
